version: '3.9'
services:
  
  postgres:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    networks:
      - default
    