name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Clear Buildx cache
        run: docker buildx prune --all --force

      - name: Restart Buildx
        run: |
          docker buildx rm mybuilder || true
          docker buildx create --name mybuilder --use --driver docker-container
          docker buildx inspect --bootstrap

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the short SHA of the commit
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Print environment variables
        run: env

      - name: Print Docker version
        run: docker version

      - name: Print Docker info
        run: docker info

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.4.1
        with:
          context: ./Hi–°lass.Backend/
          push: true
          tags: |
            alesban/hiclass-api:latest
            alesban/hiclass-api:${{ env.SHORT_SHA }}
